version: '2'

services:
  suretrend5:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  hygiena:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
